// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sacmy.Server.DatabaseContext;

namespace sacmy.Server.Migrations
{
    [DbContext(typeof(SafeenCompanyDbContext))]
    [Migration("20231214125300_UpdateOrderTrackingStructure")]
    partial class UpdateOrderTrackingStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // The rest of your model configuration will be added by EF Core
#pragma warning restore 612, 618
        }
    }
}
